"""
V3 MIS Report Agent.
Generates daily owner MIS reports using Mistral 7B for professional prose,
sends via Gmail SMTP, and logs to mis_report_log.

Key features:
- Mistral 7B AI-generated professional daily briefing (200-1000 words)
- 6-section structured report with executive summary
- Quality validation (word count, section checks)
- Automatic regeneration on quality failure
- Fallback to plain-text data table if AI fails completely
"""

import logging
import os
from datetime import datetime, timezone
from datetime import date as date_type
from uuid import uuid4

from src.database.models import EmailLog, MisReportLog
from src.gmail.gmail_sender import gmail_sender
from src.models.ollama_mistral import OllamaMistral

logger = logging.getLogger(__name__)

# Quality thresholds
MIN_REPORT_WORDS = 150
MAX_REPORT_WORDS = 1200
MAX_REGENERATION_ATTEMPTS = 2


def utc_now():
    return datetime.now(timezone.utc)


class MisReportAgent:
    """Build, validate, and persist the daily MIS report using Mistral 7B."""

    def __init__(self, db_session, email_sender=None):
        self.db = db_session
        self.email_sender = email_sender or gmail_sender
        self.ai_model = OllamaMistral()
        self.factory_name = os.environ.get("FACTORY_NAME", "PlantMind AI Factory")

    def build_report_body(self, report_date: str, summary: dict) -> str:
        """
        Generate a professional MIS report using Mistral 7B.

        Attempts AI generation with quality validation.
        Falls back to structured plain-text if AI fails.

        Args:
            report_date: ISO date string (YYYY-MM-DD)
            summary: dict of metrics from MisDataCollector

        Returns:
            Report body text (200-1000 words, 6 sections)
        """
        for attempt in range(1, MAX_REGENERATION_ATTEMPTS + 1):
            try:
                body = self._generate_ai_report(report_date, summary)

                # Quality gate
                is_valid, reason = self._validate_report_quality(body)
                if is_valid:
                    logger.info(
                        "MIS report generated by Mistral 7B (attempt %d, %d words)",
                        attempt,
                        len(body.split()),
                    )
                    return body
                else:
                    logger.warning(
                        "MIS report quality check failed (attempt %d): %s",
                        attempt,
                        reason,
                    )

            except Exception as e:
                logger.error("Mistral 7B MIS report generation failed (attempt %d): %s", attempt, e)

        # All AI attempts exhausted — use fallback
        logger.warning("All AI attempts failed — using fallback plain-text report")
        return self._build_fallback_report(report_date, summary)

    def log_report(self, report_date: str, owner_email: str, body: str):
        """
        Send the MIS report email and persist logs.

        Writes to both email_log (outbound email tracking)
        and mis_report_log (report-specific tracking).
        """
        subject = f"Daily MIS Report - {report_date}"

        # Build summary stats for HTML email template
        summary_stats = self._extract_stats_from_body(body)

        send_result = self.email_sender.send_mis_report(
            owner_email=owner_email,
            report_date=report_date,
            ai_generated_report=body,
            summary_stats=summary_stats,
        )
        send_success = bool(send_result.get("success"))
        attempts = int(send_result.get("attempts", 0))
        error_details = send_result.get("error")

        # Log to email_log
        email_log = EmailLog(
            gmail_message_id=f"mis-{report_date}-{uuid4().hex[:10]}",
            direction="out",
            from_address=self.email_sender.username if hasattr(self.email_sender, 'username') else "factory@plantmind.local",
            to_address=owner_email,
            subject=subject,
            body_summary=body[:5000],
            attachment_name="",
            filter_decision="process",
            processing_status="success" if send_success else "error",
            linked_order_id=None,
            error_details=error_details,
            processed_at=utc_now(),
        )
        self.db.add(email_log)

        # Log to mis_report_log
        try:
            parsed_date = datetime.strptime(report_date, "%Y-%m-%d").date()
        except ValueError:
            parsed_date = date_type.today()

        mis_log = MisReportLog(
            report_date=parsed_date,
            owner_email=owner_email,
            email_subject=subject,
            report_body=body[:10000],
            send_status="sent" if send_success else "failed",
            attempts=attempts,
            error_details=error_details,
            triggered_by="v3_mis_report_job",
        )
        self.db.add(mis_log)

        logger.info(
            "MIS report logged: date=%s, email_%s to %s",
            report_date,
            "sent" if send_success else "failed",
            owner_email,
        )
        return subject

    # ------------------------------------------------------------------
    # AI report generation
    # ------------------------------------------------------------------

    def _generate_ai_report(self, report_date: str, summary: dict) -> str:
        """Generate AI report using Mistral 7B with a structured prompt."""
        prompt = f"""You are the senior operations analyst at {self.factory_name}, a plastic injection moulding factory.
Write a professional Daily MIS (Management Information System) Report for the factory owner.

Report Date: {report_date}

Today's Key Metrics:
- Active orders (new/scheduled/in_production/awaiting_material): {summary.get('active_orders', 0)}
- Completed orders (ready for dispatch): {summary.get('completed_orders', 0)}
- Dispatched orders (sent to customer): {summary.get('dispatched_orders', 0)}
- Low stock materials (below reorder level): {summary.get('low_stock_materials', 0)}
- Pending reorders (awaiting supplier delivery): {summary.get('pending_reorders', 0)}
- Running machines: {summary.get('running_machines', 0)} / {summary.get('total_machines', 0)} total
- Delayed production schedules: {summary.get('delayed_schedules', 0)}

Write the report with these 6 sections:
1. EXECUTIVE SUMMARY — 2-3 sentence overview of factory status
2. ORDER STATUS — Active, completed, dispatched breakdown with observations
3. PRODUCTION STATUS — Machine utilization, delays, and throughput commentary
4. INVENTORY & SUPPLY CHAIN — Stock levels, low-stock alerts, pending reorders
5. RISK ALERTS — Any delays, low stock, or machine issues that need attention
6. RECOMMENDATIONS — 2-3 actionable items for the owner

Requirements:
- Total length: 200-500 words
- Use clear section headers with the names above
- Be data-driven — reference the specific numbers
- Professional tone suitable for a factory owner
- If all metrics look healthy, say so positively
- If there are problems, flag them clearly with suggested actions
- End with a brief closing line

Write the complete report now:"""

        response = self.ai_model.generate_response(prompt, stream=False)
        return response.strip()

    # ------------------------------------------------------------------
    # Quality validation
    # ------------------------------------------------------------------

    def _validate_report_quality(self, body: str) -> tuple[bool, str]:
        """
        Validate the AI-generated report meets quality standards.

        Returns:
            Tuple of (is_valid, reason_if_invalid)
        """
        word_count = len(body.split())

        if word_count < MIN_REPORT_WORDS:
            return False, f"Too short ({word_count} words, minimum {MIN_REPORT_WORDS})"

        if word_count > MAX_REPORT_WORDS:
            return False, f"Too long ({word_count} words, maximum {MAX_REPORT_WORDS})"

        # Check for at least 3 of the 6 expected section headers
        expected_sections = [
            "EXECUTIVE SUMMARY",
            "ORDER STATUS",
            "PRODUCTION STATUS",
            "INVENTORY",
            "RISK",
            "RECOMMENDATION",
        ]
        found_sections = sum(
            1 for s in expected_sections if s.lower() in body.lower()
        )
        if found_sections < 3:
            return False, f"Only {found_sections}/6 expected sections found"

        return True, "OK"

    # ------------------------------------------------------------------
    # Fallback report (when AI is unavailable)
    # ------------------------------------------------------------------

    def _build_fallback_report(self, report_date: str, summary: dict) -> str:
        """Build a structured plain-text report when AI is unavailable."""
        active = summary.get("active_orders", 0)
        completed = summary.get("completed_orders", 0)
        dispatched = summary.get("dispatched_orders", 0)
        low_stock = summary.get("low_stock_materials", 0)
        pending_reorders = summary.get("pending_reorders", 0)
        running = summary.get("running_machines", 0)
        total = summary.get("total_machines", 0)
        delayed = summary.get("delayed_schedules", 0)

        utilization = f"{(running/total*100):.0f}%" if total > 0 else "N/A"

        risk_items = []
        if delayed > 0:
            risk_items.append(f"  ⚠️  {delayed} production schedule(s) are delayed — review immediately")
        if low_stock > 0:
            risk_items.append(f"  ⚠️  {low_stock} material(s) below reorder level — check supplier status")
        if not risk_items:
            risk_items.append("  ✅  No critical risks identified today")

        risks_text = "\n".join(risk_items)

        return f"""{self.factory_name} — Daily MIS Report
Date: {report_date}

═══════════════════════════════════════
EXECUTIVE SUMMARY
═══════════════════════════════════════
Factory operations report for {report_date}. Currently tracking {active} active order(s), with {completed} completed and {dispatched} dispatched. Machine utilization is at {utilization}.

═══════════════════════════════════════
ORDER STATUS
═══════════════════════════════════════
  Active Orders:       {active}
  Completed Orders:    {completed}
  Dispatched Orders:   {dispatched}

═══════════════════════════════════════
PRODUCTION STATUS
═══════════════════════════════════════
  Running Machines:    {running} / {total}
  Machine Utilization: {utilization}
  Delayed Schedules:   {delayed}

═══════════════════════════════════════
INVENTORY & SUPPLY CHAIN
═══════════════════════════════════════
  Low Stock Materials:   {low_stock}
  Pending Reorders:      {pending_reorders}

═══════════════════════════════════════
RISK ALERTS
═══════════════════════════════════════
{risks_text}

═══════════════════════════════════════
RECOMMENDATIONS
═══════════════════════════════════════
  1. Review any delayed schedules and consider resource reallocation
  2. Follow up on pending supplier reorders for delivery timelines
  3. Monitor machine maintenance schedules for upcoming service dates

Report generated automatically by PlantMind AI at {utc_now().strftime('%H:%M UTC')}.
"""

    def _extract_stats_from_body(self, body: str) -> dict:
        """Extract key stats for the HTML email template cards."""
        # This provides the stat cards in the HTML email header
        # It's a best-effort extraction from the text
        import re

        stats = {}
        patterns = {
            "Active Orders": r"active.*?(\d+)",
            "Completed": r"completed.*?(\d+)",
            "Dispatched": r"dispatched.*?(\d+)",
        }
        for label, pattern in patterns.items():
            match = re.search(pattern, body, re.IGNORECASE)
            if match:
                stats[label] = match.group(1)

        return stats
